### ISSUE TITLE
Learn Test Issue

### ISSUE THREAD

**Issue by livfrediehard** [learn-co-curriculum/ttt-1-welcome-rb#32]
Get the following issue when running learn test.

![Screen Shot 2021-06-23 at 2 10 09 PM](https://user-images.githubusercontent.com/63824731/123148214-f55c0f00-d42d-11eb-96c9-90f5cf90b2f4.png)

**Comment by graciemcguire** [comment]
Thanks for raising this issue. Based on your image, it looks like the issue may be related to your environment setup rather than with the lesson itself or the instructions. The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support.

To get help with your question, you should either: 

- Reach out to your instructor (if you've started the program and have an instructor)
- Use the [#js-prework-support](https://flatiron-school.slack.com/archives/C01KEEVJU3Y) Slack channel (if you're working on the prework)
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
